#@ load("@ytt:data", "data")

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: bert-spam-detector
  namespace: argo
spec:
  entrypoint: bert-spam-detector
  templates:
    - name: bert-spam-detector
      steps:
        - - name: bert-spam-detector-training
            template: bert-spam-detector-training
        - - name: bert-spam-detector-archive
            template: bert-spam-detector-archive

    - name: bert-spam-detector-training
      container:
        image: localhost:32000/ml-playground:latest
        command: ["python"]
        args:
          - ./models/bert-spam-detector/train.py
          - --training_data_file
          - ./models/bert-spam-detector/data/spam-labels.csv
          - --model_output_dir
          - /var/ml/data/torchserve/.staging/bert-spam-detector/1.0/
          - --transformer_cache_dir
          - /var/ml/data/cache/
          - --bert_revision
          - 0a6aa9128b6194f4f3c4db429b6cb4891cdb421b
        resources:
          limits:
            nvidia.com/gpu: "1"
        volumeMounts:
          - name: ml-volume
            mountPath: /var/ml/data
    - name: bert-spam-detector-archive
      container:
        image: localhost:32000/ml-playground:latest
        command: ["torch-model-archiver"]
        args:
          - --model-name
          - bert-spam-detector
          - --version
          - "1.0"
          - --serialized-file
          - /var/ml/data/torchserve/.staging/bert-spam-detector/1.0/pytorch_model.bin
          - --handler
          - ./models/bert-spam-detector/transformerhandler.py
          - --export-path
          - /var/ml/data/torchserve/
          - --force
          - --extra-files
          - /var/ml/data/cache/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/config.json,/var/ml/data/cache/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/tokenizer.json,/var/ml/data/cache/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/tokenizer_config.json,/var/ml/data/cache/models--bert-base-uncased/snapshots/0a6aa9128b6194f4f3c4db429b6cb4891cdb421b/vocab.txt
        volumeMounts:
          - name: ml-volume
            mountPath: /var/ml/data

  volumes:
    - name: ml-volume
      hostPath:
        path: #@ data.values.model_dir
        type: Directory