version: '3'

dotenv: ['.env']

includes:
  infrastructure: ./infrastructure
  models: ./models

vars:
  DOCKER_REPOSITORY: '{{if .REMOTE_HOST}}{{.REMOTE_HOST}}{{else}}localhost{{end}}:32000' # 32000 microk8s registry port

tasks:
  docker-build:
    cmds:
      - docker build . -t {{.DOCKER_REPOSITORY}}/ml-playground:latest

  docker-push:
    cmds:
      - docker push {{.DOCKER_REPOSITORY}}/ml-playground

  docker:
    cmds:
      - task: docker-build
      - task: docker-push