version: '3'

dotenv: ['.env']

includes:
  infrastructure: ./infrastructure
  models: ./models

vars:
  DOCKER_REPOSITORY: '{{if .REMOTE_HOST}}{{.REMOTE_HOST}}{{else}}localhost{{end}}:32000' # 32000 microk8s registry port

tasks:
  docker-build:
    cmds:
      - docker build . -t {{.DOCKER_REPOSITORY}}/ml-playground:latest

  docker-push:
    cmds:
      - docker push {{.DOCKER_REPOSITORY}}/ml-playground

  docker:
    cmds:
      - task: docker-build
      - task: docker-push

  torchserve-deploy:
    cmds:
      - kubectl apply -f k8s/torchserve-namespace.yml
      - ytt --data-value model_dir={{.MODEL_STORE_DIR}} -f k8s/torchserve.yml | kubectl apply -f -
      - kubectl apply -f k8s/torchserve-service.yml
      - kubectl apply -f k8s/torchserve-servicemonitor.yml

  torchserve-inference-api:
    cmds:
      - "kubectl -n torchserve port-forward service/torchserve 8080:8080"