version: '3'

env:
  DOCKER_REPOSITORY: '{{if .REMOTE_HOST}}{{.REMOTE_HOST}}{{else}}localhost{{end}}:32000' # 32000 microk8s registry port

tasks:
  deploy-train:
    cmds:
      - kubectl scale --replicas=0 deployment/torchserve -n torchserve
      - ytt --data-value model_dir={{.MODEL_STORE_DIR}} -f k8s/workflow-train.yml | kubectl create -f -
      - kubectl scale --replicas=1 deployment/torchserve -n torchserve