version: '3'

env:
  DOCKER_REPOSITORY: '{{if .REMOTE_HOST}}{{.REMOTE_HOST}}{{else}}localhost{{end}}:32000' # 32000 microk8s registry port

tasks:
  deploy-train:
    cmds:
      - ytt --data-value model_dir={{.MODEL_STORE_DIR}} -f k8s/train.yml | kubectl create -f -

  deploy-clean-torchserve:
    cmds:
      - kubectl delete deploy bert-spam-detector -n inference

  deploy-torchserve:
    cmds:
      - ytt --data-value model_dir={{.MODEL_STORE_DIR}} -f k8s/torchserve.yml | kubectl apply -f -
      - kubectl apply -f k8s/torchserve-service.yml
      - kubectl apply -f k8s/torchserve-servicemonitor.yml

  serve-torch:
    cmds:
      - "kubectl -n inference port-forward svc/bert-spam-detector 8080:8080"

  train:
    cmds:
      - task: docker
      - task: deploy-train